name: backend testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruff
        run: pipx install ruff

      - name: Lint with Ruff
        run: ruff check .
        working-directory: backend
